### PR TITLE
Feature/header logo

### PR DESCRIPTION
**Pull request by markbrough**
Would probably be good to move the logo text out of the graphic though

### CODE REVIEW

**Comment by olafveerman** [comment]
Great to see a logo up!

Couple of questions:
- do you have the logo in SVG? It would be great to replace the bitmap for vector.
- we'll have to address the header on the smaller breakpoints, currently it completely breaks header and navigation on mobile.
- can the name of the site be regular text, instead of part of the image?

**Comment by claudioccm** [comment]
Yes, we can do both. I will push once I figure this out.

**Comment by ricardoduplos** [comment]
I can take a look on this as well and figure out the best solution. I'm familiar with the markup and styles.

**Comment by claudioccm** [comment]
@ricardomestre, here are 2 SVGs for the logo. 
https://www.dropbox.com/s/l756s1z18xt66hn/logo.zip?dl=0

My main concern is the weird SVG generated by illustrator. I never understand how it works.
The font is Signika Regular.

We should use the Negative version, in this case.
Let me know if you need anything else from me. 
Cheers,

**Comment by ricardoduplos** [comment]
Thanks for the logo, @claudioccm. I'll see what I can do.

**Comment by markbrough** [comment]
@olafveerman, @ricardomestre - sorry, I just realised that the header navigation is broken and particularly on mobile. I may have implemented it slightly better in the program [landing / documentation site](http://procurement-analytics.github.io/), in case that is any good (though if you are able to update the logo, I'm also happy to just copy that across).

**Comment by ricardoduplos** [comment]
Problem solved. There's a new SVG version in place. The navigation now appears stacked on mobile to give room to the logo.

Please check and merge: https://github.com/procurement-analytics/procurement-analytics/pull/18

**Pull request merged**
